// Meeting Summary Email System

import { Recording } from '@/lib/types/voice-notes'

export interface EmailRecipient {
  email: string
  name?: string
}

export interface MeetingSummaryEmail {
  to: EmailRecipient[]
  subject: string
  htmlBody: string
  textBody: string
}

// Generate email from recording
export function generateMeetingSummaryEmail(
  recording: Recording,
  attendees: string[]
): MeetingSummaryEmail {
  const date = recording.date.toLocaleDateString()
  const time = recording.date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  const duration = `${Math.floor(recording.duration / 60)} min`

  const subject = `Meeting Summary: ${recording.title}`

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6; color: #374151; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #DC2626 0%, #991B1B 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }
    .content { background: white; padding: 30px; border: 1px solid #E5E7EB; border-top: none; }
    .section { margin: 24px 0; }
    .section-title { font-size: 18px; font-weight: 600; color: #1F2937; margin-bottom: 12px; border-bottom: 2px solid #E5E7EB; padding-bottom: 8px; }
    .meta { color: #6B7280; font-size: 14px; margin-bottom: 20px; }
    .summary-box { background: #EFF6FF; border-left: 4px solid #3B82F6; padding: 16px; border-radius: 4px; margin: 16px 0; }
    .item-list { list-style: none; padding: 0; }
    .item-list li { padding: 8px 0; border-bottom: 1px solid #F3F4F6; }
    .item-list li:last-child { border-bottom: none; }
    .checkbox { display: inline-block; width: 16px; height: 16px; border: 2px solid #D1D5DB; border-radius: 3px; margin-right: 8px; vertical-align: middle; }
    .question { background: #F3E8FF; padding: 12px; border-radius: 6px; margin: 8px 0; }
    .decision { background: #DCFCE7; padding: 12px; border-radius: 6px; margin: 8px 0; }
    .footer { text-align: center; padding: 20px; color: #9CA3AF; font-size: 12px; }
    .button { display: inline-block; padding: 12px 24px; background: #DC2626; color: white; text-decoration: none; border-radius: 6px; font-weight: 500; margin: 16px 0; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 style="margin: 0; font-size: 24px;">🎙️ Meeting Summary</h1>
      <p style="margin: 10px 0 0 0; opacity: 0.9;">${recording.title}</p>
    </div>
    
    <div class="content">
      <div class="meta">
        📅 ${date} at ${time} • ⏱️ ${duration}
      </div>

      ${recording.summary ? `
      <div class="summary-box">
        <strong style="display: block; margin-bottom: 8px;">📋 Summary</strong>
        <p style="margin: 0;">${recording.summary}</p>
      </div>
      ` : ''}

      ${recording.questions && recording.questions.length > 0 ? `
      <div class="section">
        <div class="section-title">❓ Questions Raised (${recording.questions.length})</div>
        ${recording.questions.map(q => `<div class="question">${q}</div>`).join('')}
      </div>
      ` : ''}

      ${recording.decisions && recording.decisions.length > 0 ? `
      <div class="section">
        <div class="section-title">✅ Decisions Made (${recording.decisions.length})</div>
        ${recording.decisions.map(d => `<div class="decision">${d}</div>`).join('')}
      </div>
      ` : ''}

      ${recording.actionItems && recording.actionItems.length > 0 ? `
      <div class="section">
        <div class="section-title">✅ Action Items</div>
        <ul class="item-list">
          ${recording.actionItems.map(item => `
            <li>
              <span class="checkbox"></span>
              ${item}
            </li>
          `).join('')}
        </ul>
      </div>
      ` : ''}

      ${recording.commitments && recording.commitments.length > 0 ? `
      <div class="section">
        <div class="section-title">🎯 Commitments</div>
        <ul class="item-list">
          ${recording.commitments.map(c => `<li>→ ${c}</li>`).join('')}
        </ul>
      </div>
      ` : ''}

      ${recording.nextSteps && recording.nextSteps.length > 0 ? `
      <div class="section">
        <div class="section-title">🔜 Next Steps</div>
        <ul class="item-list">
          ${recording.nextSteps.map((step, i) => `<li>${i + 1}. ${step}</li>`).join('')}
        </ul>
      </div>
      ` : ''}

      <div style="text-align: center; margin-top: 32px;">
        <a href="${process.env.NEXT_PUBLIC_APP_URL}/voice-notes" class="button">
          View Full Recording & Transcript
        </a>
      </div>
    </div>

    <div class="footer">
      <p>This summary was automatically generated by Voice Notes AI</p>
      <p style="margin-top: 8px;">
        <a href="${process.env.NEXT_PUBLIC_APP_URL}" style="color: #9CA3AF;">Ludwitt</a>
      </p>
    </div>
  </div>
</body>
</html>
  `.trim()

  const textBody = `
Meeting Summary: ${recording.title}
${date} at ${time} • ${duration}

${recording.summary ? `SUMMARY:\n${recording.summary}\n` : ''}

${recording.questions && recording.questions.length > 0 ? `
QUESTIONS RAISED (${recording.questions.length}):
${recording.questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}
` : ''}

${recording.decisions && recording.decisions.length > 0 ? `
DECISIONS MADE (${recording.decisions.length}):
${recording.decisions.map((d, i) => `${i + 1}. ${d}`).join('\n')}
` : ''}

${recording.actionItems && recording.actionItems.length > 0 ? `
ACTION ITEMS:
${recording.actionItems.map(item => `☐ ${item}`).join('\n')}
` : ''}

${recording.commitments && recording.commitments.length > 0 ? `
COMMITMENTS:
${recording.commitments.map(c => `→ ${c}`).join('\n')}
` : ''}

${recording.nextSteps && recording.nextSteps.length > 0 ? `
NEXT STEPS:
${recording.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}
` : ''}

---
View full recording: ${process.env.NEXT_PUBLIC_APP_URL}/voice-notes

This summary was automatically generated by Voice Notes AI
`.trim()

  return {
    to: attendees.map(email => ({ email })),
    subject,
    htmlBody,
    textBody
  }
}

// Send email via your existing email service
export async function sendMeetingSummary(
  recording: Recording,
  attendees: string[],
  senderEmail: string
): Promise<void> {
  const email = generateMeetingSummaryEmail(recording, attendees)

  // Use your existing email service (from /lib/integrations/email/service.ts)
  const response = await fetch('/api/email/send-meeting-summary', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      ...email,
      from: senderEmail
    })
  })

  if (!response.ok) {
    throw new Error('Failed to send email')
  }
}

