/**
 * Math symbol data for the symbol picker.
 *
 * Contains all symbol categories and their individual symbols
 * used by MathSymbolPicker and related components.
 */

export type SymbolCategory =
  | 'arithmetic'
  | 'algebra'
  | 'geometry'
  | 'calculus'
  | 'matrices'
  | 'greek'
  | 'sets'

export interface MathSymbol {
  display: string
  insert: string
  label: string
}

export const SYMBOL_CATEGORIES: Record<SymbolCategory, { name: string; icon: string; symbols: MathSymbol[] }> = {
  arithmetic: {
    name: 'Arithmetic',
    icon: '+-',
    symbols: [
      { display: '+', insert: '+', label: 'Plus' },
      { display: '−', insert: '-', label: 'Minus' },
      { display: '×', insert: '×', label: 'Times' },
      { display: '÷', insert: '÷', label: 'Divide' },
      { display: '=', insert: '=', label: 'Equals' },
      { display: '≠', insert: '≠', label: 'Not equal' },
      { display: '<', insert: '<', label: 'Less than' },
      { display: '>', insert: '>', label: 'Greater than' },
      { display: '≤', insert: '≤', label: 'Less or equal' },
      { display: '≥', insert: '≥', label: 'Greater or equal' },
      { display: '±', insert: '±', label: 'Plus minus' },
      { display: '∓', insert: '∓', label: 'Minus plus' },
      { display: '·', insert: '·', label: 'Dot multiply' },
      { display: '/', insert: '/', label: 'Slash' },
      { display: '%', insert: '%', label: 'Percent' },
      { display: '‰', insert: '‰', label: 'Per mille' },
      { display: '∞', insert: '∞', label: 'Infinity' },
      { display: '≈', insert: '≈', label: 'Approximately' },
      { display: '≡', insert: '≡', label: 'Identical to' },
      { display: '≢', insert: '≢', label: 'Not identical' },
      { display: '∝', insert: '∝', label: 'Proportional to' },
      { display: '≪', insert: '≪', label: 'Much less than' },
      { display: '≫', insert: '≫', label: 'Much greater than' },
      { display: '⌊ ⌋', insert: '⌊⌋', label: 'Floor' },
      { display: '⌈ ⌉', insert: '⌈⌉', label: 'Ceiling' },
      { display: '| |', insert: '||', label: 'Absolute value' },
      { display: '( )', insert: '()', label: 'Parentheses' },
      { display: '[ ]', insert: '[]', label: 'Brackets' },
      { display: '{ }', insert: '{}', label: 'Braces' },
      { display: '!', insert: '!', label: 'Factorial' },
    ]
  },
  algebra: {
    name: 'Algebra',
    icon: 'xⁿ',
    symbols: [
      { display: 'x', insert: 'x', label: 'Variable x' },
      { display: 'y', insert: 'y', label: 'Variable y' },
      { display: 'z', insert: 'z', label: 'Variable z' },
      { display: 'n', insert: 'n', label: 'Variable n' },
      { display: 'x²', insert: 'x²', label: 'X squared' },
      { display: 'x³', insert: 'x³', label: 'X cubed' },
      { display: 'xⁿ', insert: 'xⁿ', label: 'X to the n' },
      { display: '√', insert: '√', label: 'Square root' },
      { display: '∛', insert: '∛', label: 'Cube root' },
      { display: '∜', insert: '∜', label: 'Fourth root' },
      { display: '⁰', insert: '⁰', label: 'Superscript 0' },
      { display: '¹', insert: '¹', label: 'Superscript 1' },
      { display: '²', insert: '²', label: 'Superscript 2' },
      { display: '³', insert: '³', label: 'Superscript 3' },
      { display: '⁴', insert: '⁴', label: 'Superscript 4' },
      { display: '⁵', insert: '⁵', label: 'Superscript 5' },
      { display: '⁶', insert: '⁶', label: 'Superscript 6' },
      { display: '⁷', insert: '⁷', label: 'Superscript 7' },
      { display: '⁸', insert: '⁸', label: 'Superscript 8' },
      { display: '⁹', insert: '⁹', label: 'Superscript 9' },
      { display: '⁺', insert: '⁺', label: 'Superscript plus' },
      { display: '⁻', insert: '⁻', label: 'Superscript minus' },
      { display: 'ⁿ', insert: 'ⁿ', label: 'Superscript n' },
      { display: '₀', insert: '₀', label: 'Subscript 0' },
      { display: '₁', insert: '₁', label: 'Subscript 1' },
      { display: '₂', insert: '₂', label: 'Subscript 2' },
      { display: '₃', insert: '₃', label: 'Subscript 3' },
      { display: '₄', insert: '₄', label: 'Subscript 4' },
      { display: '₅', insert: '₅', label: 'Subscript 5' },
      { display: 'ₙ', insert: 'ₙ', label: 'Subscript n' },
      { display: 'ₓ', insert: 'ₓ', label: 'Subscript x' },
      { display: '½', insert: '½', label: 'One half' },
      { display: '⅓', insert: '⅓', label: 'One third' },
      { display: '¼', insert: '¼', label: 'One quarter' },
      { display: '⅕', insert: '⅕', label: 'One fifth' },
      { display: '⅔', insert: '⅔', label: 'Two thirds' },
      { display: '¾', insert: '¾', label: 'Three quarters' },
      { display: '⅖', insert: '⅖', label: 'Two fifths' },
      { display: '⅗', insert: '⅗', label: 'Three fifths' },
      { display: '⅘', insert: '⅘', label: 'Four fifths' },
    ]
  },
  geometry: {
    name: 'Geometry',
    icon: '△',
    symbols: [
      { display: '°', insert: '°', label: 'Degree' },
      { display: '′', insert: '′', label: 'Arc minute' },
      { display: '″', insert: '″', label: 'Arc second' },
      { display: '∠', insert: '∠', label: 'Angle' },
      { display: '∟', insert: '∟', label: 'Right angle' },
      { display: '⊥', insert: '⊥', label: 'Perpendicular' },
      { display: '∥', insert: '∥', label: 'Parallel' },
      { display: '∦', insert: '∦', label: 'Not parallel' },
      { display: '△', insert: '△', label: 'Triangle' },
      { display: '▷', insert: '▷', label: 'Right triangle' },
      { display: '□', insert: '□', label: 'Square' },
      { display: '▢', insert: '▢', label: 'Rectangle' },
      { display: '◇', insert: '◇', label: 'Diamond' },
      { display: '○', insert: '○', label: 'Circle' },
      { display: '⊙', insert: '⊙', label: 'Circle with center' },
      { display: '⬡', insert: '⬡', label: 'Hexagon' },
      { display: '⬢', insert: '⬢', label: 'Pentagon' },
      { display: '∼', insert: '∼', label: 'Similar' },
      { display: '≅', insert: '≅', label: 'Congruent' },
      { display: '∴', insert: '∴', label: 'Therefore' },
      { display: '∵', insert: '∵', label: 'Because' },
      { display: '⟂', insert: '⟂', label: 'Orthogonal' },
      { display: '→', insert: '→', label: 'Ray/Arrow right' },
      { display: '←', insert: '←', label: 'Arrow left' },
      { display: '↔', insert: '↔', label: 'Line segment' },
      { display: '⃗', insert: '⃗', label: 'Vector arrow' },
      { display: 'π', insert: 'π', label: 'Pi' },
      { display: 'τ', insert: 'τ', label: 'Tau' },
      { display: 'sin', insert: 'sin', label: 'Sine' },
      { display: 'cos', insert: 'cos', label: 'Cosine' },
      { display: 'tan', insert: 'tan', label: 'Tangent' },
      { display: 'sec', insert: 'sec', label: 'Secant' },
      { display: 'csc', insert: 'csc', label: 'Cosecant' },
      { display: 'cot', insert: 'cot', label: 'Cotangent' },
    ]
  },
  calculus: {
    name: 'Calculus',
    icon: '∫',
    symbols: [
      { display: '∫', insert: '∫', label: 'Integral' },
      { display: '∬', insert: '∬', label: 'Double integral' },
      { display: '∭', insert: '∭', label: 'Triple integral' },
      { display: '∮', insert: '∮', label: 'Contour integral' },
      { display: '∯', insert: '∯', label: 'Surface integral' },
      { display: '∰', insert: '∰', label: 'Volume integral' },
      { display: '∂', insert: '∂', label: 'Partial derivative' },
      { display: 'ⅆ', insert: 'ⅆ', label: 'Differential d' },
      { display: '∇', insert: '∇', label: 'Nabla/Del' },
      { display: 'Δ', insert: 'Δ', label: 'Delta (change)' },
      { display: 'ε', insert: 'ε', label: 'Epsilon' },
      { display: 'δ', insert: 'δ', label: 'Delta small' },
      { display: 'lim', insert: 'lim', label: 'Limit' },
      { display: '→', insert: '→', label: 'Approaches' },
      { display: '∞', insert: '∞', label: 'Infinity' },
      { display: 'Σ', insert: 'Σ', label: 'Summation' },
      { display: '∏', insert: '∏', label: 'Product' },
      { display: 'dx', insert: 'dx', label: 'dx' },
      { display: 'dy', insert: 'dy', label: 'dy' },
      { display: 'dt', insert: 'dt', label: 'dt' },
      { display: 'f(x)', insert: 'f(x)', label: 'Function of x' },
      { display: "f'(x)", insert: "f'(x)", label: 'First derivative' },
      { display: "f''(x)", insert: "f''(x)", label: 'Second derivative' },
      { display: 'dy/dx', insert: 'dy/dx', label: 'Derivative' },
      { display: '∂y/∂x', insert: '∂y/∂x', label: 'Partial derivative' },
      { display: 'd²y/dx²', insert: 'd²y/dx²', label: 'Second derivative' },
    ]
  },
  matrices: {
    name: 'Matrices',
    icon: '⌈⌉',
    symbols: [
      { display: '⎡ ⎤', insert: '⎡⎤', label: 'Matrix bracket top' },
      { display: '⎢ ⎥', insert: '⎢⎥', label: 'Matrix bracket middle' },
      { display: '⎣ ⎦', insert: '⎣⎦', label: 'Matrix bracket bottom' },
      { display: '⎛ ⎞', insert: '⎛⎞', label: 'Parenthesis top' },
      { display: '⎜ ⎟', insert: '⎜⎟', label: 'Parenthesis middle' },
      { display: '⎝ ⎠', insert: '⎝⎠', label: 'Parenthesis bottom' },
      { display: '|A|', insert: '|A|', label: 'Determinant' },
      { display: 'det', insert: 'det', label: 'Determinant word' },
      { display: 'A⁻¹', insert: 'A⁻¹', label: 'Inverse' },
      { display: 'Aᵀ', insert: 'Aᵀ', label: 'Transpose' },
      { display: '⋮', insert: '⋮', label: 'Vertical dots' },
      { display: '⋯', insert: '⋯', label: 'Horizontal dots' },
      { display: '⋱', insert: '⋱', label: 'Diagonal dots' },
      { display: '×', insert: '×', label: 'Cross product' },
      { display: '·', insert: '·', label: 'Dot product' },
      { display: '⊗', insert: '⊗', label: 'Tensor product' },
      { display: '⊕', insert: '⊕', label: 'Direct sum' },
      { display: 'rank', insert: 'rank', label: 'Rank' },
      { display: 'tr', insert: 'tr', label: 'Trace' },
      { display: 'dim', insert: 'dim', label: 'Dimension' },
    ]
  },
  greek: {
    name: 'Greek',
    icon: 'αβ',
    symbols: [
      { display: 'α', insert: 'α', label: 'Alpha' },
      { display: 'β', insert: 'β', label: 'Beta' },
      { display: 'γ', insert: 'γ', label: 'Gamma' },
      { display: 'δ', insert: 'δ', label: 'Delta' },
      { display: 'ε', insert: 'ε', label: 'Epsilon' },
      { display: 'ζ', insert: 'ζ', label: 'Zeta' },
      { display: 'η', insert: 'η', label: 'Eta' },
      { display: 'θ', insert: 'θ', label: 'Theta' },
      { display: 'ι', insert: 'ι', label: 'Iota' },
      { display: 'κ', insert: 'κ', label: 'Kappa' },
      { display: 'λ', insert: 'λ', label: 'Lambda' },
      { display: 'μ', insert: 'μ', label: 'Mu' },
      { display: 'ν', insert: 'ν', label: 'Nu' },
      { display: 'ξ', insert: 'ξ', label: 'Xi' },
      { display: 'ο', insert: 'ο', label: 'Omicron' },
      { display: 'π', insert: 'π', label: 'Pi' },
      { display: 'ρ', insert: 'ρ', label: 'Rho' },
      { display: 'σ', insert: 'σ', label: 'Sigma' },
      { display: 'τ', insert: 'τ', label: 'Tau' },
      { display: 'υ', insert: 'υ', label: 'Upsilon' },
      { display: 'φ', insert: 'φ', label: 'Phi' },
      { display: 'χ', insert: 'χ', label: 'Chi' },
      { display: 'ψ', insert: 'ψ', label: 'Psi' },
      { display: 'ω', insert: 'ω', label: 'Omega' },
      { display: 'Γ', insert: 'Γ', label: 'Gamma (upper)' },
      { display: 'Δ', insert: 'Δ', label: 'Delta (upper)' },
      { display: 'Θ', insert: 'Θ', label: 'Theta (upper)' },
      { display: 'Λ', insert: 'Λ', label: 'Lambda (upper)' },
      { display: 'Ξ', insert: 'Ξ', label: 'Xi (upper)' },
      { display: 'Π', insert: 'Π', label: 'Pi (upper)' },
      { display: 'Σ', insert: 'Σ', label: 'Sigma (upper)' },
      { display: 'Φ', insert: 'Φ', label: 'Phi (upper)' },
      { display: 'Ψ', insert: 'Ψ', label: 'Psi (upper)' },
      { display: 'Ω', insert: 'Ω', label: 'Omega (upper)' },
    ]
  },
  sets: {
    name: 'Sets & Logic',
    icon: '∈∪',
    symbols: [
      { display: '∈', insert: '∈', label: 'Element of' },
      { display: '∉', insert: '∉', label: 'Not element of' },
      { display: '⊂', insert: '⊂', label: 'Subset' },
      { display: '⊃', insert: '⊃', label: 'Superset' },
      { display: '⊆', insert: '⊆', label: 'Subset or equal' },
      { display: '⊇', insert: '⊇', label: 'Superset or equal' },
      { display: '∪', insert: '∪', label: 'Union' },
      { display: '∩', insert: '∩', label: 'Intersection' },
      { display: '∅', insert: '∅', label: 'Empty set' },
      { display: '∁', insert: '∁', label: 'Complement' },
      { display: '\\', insert: '\\', label: 'Set minus' },
      { display: '×', insert: '×', label: 'Cartesian product' },
      { display: 'ℕ', insert: 'ℕ', label: 'Natural numbers' },
      { display: 'ℤ', insert: 'ℤ', label: 'Integers' },
      { display: 'ℚ', insert: 'ℚ', label: 'Rationals' },
      { display: 'ℝ', insert: 'ℝ', label: 'Real numbers' },
      { display: 'ℂ', insert: 'ℂ', label: 'Complex numbers' },
      { display: '∧', insert: '∧', label: 'Logical AND' },
      { display: '∨', insert: '∨', label: 'Logical OR' },
      { display: '¬', insert: '¬', label: 'Logical NOT' },
      { display: '⊕', insert: '⊕', label: 'XOR' },
      { display: '→', insert: '→', label: 'Implies' },
      { display: '↔', insert: '↔', label: 'If and only if' },
      { display: '∀', insert: '∀', label: 'For all' },
      { display: '∃', insert: '∃', label: 'There exists' },
      { display: '∄', insert: '∄', label: 'Does not exist' },
      { display: '⊢', insert: '⊢', label: 'Proves' },
      { display: '⊨', insert: '⊨', label: 'Models' },
      { display: '⊤', insert: '⊤', label: 'True' },
      { display: '⊥', insert: '⊥', label: 'False' },
    ]
  }
}

export const CATEGORY_ORDER: SymbolCategory[] = ['arithmetic', 'algebra', 'geometry', 'calculus', 'matrices', 'greek', 'sets']
