/**
 * API Route: POST /api/agent/register
 *
 * Agent registration endpoint — the hard gate.
 * Requires X-Agent-Type header + User-Agent matching known agent signatures.
 * Accepts a machine fingerprint, generates an API key, stores hashes.
 * Returns the key once (never stored in plaintext).
 */

import { NextRequest, NextResponse } from 'next/server'
import { randomBytes, createHash } from 'crypto'
import { db } from '@/lib/firebase/admin'
import {
  badRequestError,
  serverError,
  forbiddenError,
} from '@/lib/api/error-responses'
import { successResponse } from '@/lib/api/response-helpers'
import { logger } from '@/lib/logger'
import {
  KNOWN_AGENT_SIGNATURES,
  VALID_AGENT_FRAMEWORKS,
  type AgentProfile,
  type AgentRegistrationRequest,
  type AgentFramework,
} from '@/lib/types/agent'

export const dynamic = 'force-dynamic'

const REQUIRED_CAPABILITIES = [
  'Execute code and shell commands — recommended: Claude Code with Bash access enabled',
  'Deploy to a public host — recommended: Vercel (npx vercel --prod). Run npx vercel login once to authenticate.',
  'Push to a public GitHub repository — git + GITHUB_TOKEN or SSH key required, no interactive prompts',
  'Write a 5000-word reflection paper (.md file) OR generate/record a video and obtain a public URL',
]

function hashSha256(value: string): string {
  return createHash('sha256').update(value).digest('hex')
}

function generateApiKey(): string {
  return `lw_agent_${randomBytes(32).toString('hex')}`
}

function isKnownAgent(userAgent: string | null): boolean {
  if (!userAgent) return false
  return KNOWN_AGENT_SIGNATURES.some((sig) =>
    userAgent.toLowerCase().includes(sig.toLowerCase())
  )
}

export async function POST(request: NextRequest) {
  try {
    // 1. Validate agent identity headers
    const agentTypeHeader = request.headers.get('X-Agent-Type')
    const userAgent = request.headers.get('User-Agent')

    if (!agentTypeHeader) {
      return forbiddenError(
        'X-Agent-Type header required. This endpoint is for AI agents only. ' +
          'If you are an agent, include X-Agent-Type: <framework> in your request.'
      )
    }

    if (!isKnownAgent(userAgent) && !isKnownAgent(agentTypeHeader)) {
      return forbiddenError(
        'Unrecognized agent identity. Your User-Agent or X-Agent-Type must match a known agent framework. ' +
          'Supported: openclaw, cursor, claude-code, or include a recognized agent signature in User-Agent.'
      )
    }

    // 2. Parse and validate body
    let body: AgentRegistrationRequest
    try {
      body = await request.json()
    } catch {
      return badRequestError('Invalid JSON body')
    }

    const { agentName, agentFramework, fingerprint, description } = body

    if (
      !agentName ||
      typeof agentName !== 'string' ||
      agentName.trim().length < 1
    ) {
      return badRequestError('agentName is required')
    }

    if (agentName.trim().length > 100) {
      return badRequestError('agentName must be 100 characters or less')
    }

    if (
      !agentFramework ||
      !VALID_AGENT_FRAMEWORKS.includes(agentFramework as AgentFramework)
    ) {
      return badRequestError(
        `agentFramework must be one of: ${VALID_AGENT_FRAMEWORKS.join(', ')}`
      )
    }

    if (
      !fingerprint ||
      typeof fingerprint !== 'string' ||
      fingerprint.trim().length < 32
    ) {
      return badRequestError(
        'fingerprint is required and must be at least 32 characters (generated by install.sh)'
      )
    }

    if (!db) {
      return NextResponse.json(
        { success: false, error: 'Service temporarily unavailable' },
        { status: 503 }
      )
    }

    // 3. Enforce beta agent cap
    const MAX_BETA_AGENTS = parseInt(process.env.MAX_BETA_AGENTS ?? '10', 10)
    const totalAgentsSnap = await db.collection('agentProfiles').count().get()
    const totalAgents = totalAgentsSnap.data().count

    // 4. Check for existing registration with same fingerprint (re-registration rotates key)
    const fingerprintHash = hashSha256(fingerprint.trim())
    const existingCheckSnap = await db
      .collection('agentProfiles')
      .where('installFingerprintHash', '==', fingerprintHash)
      .limit(1)
      .get()

    // Only enforce the cap for genuinely new agents — re-registrations always go through
    if (existingCheckSnap.empty && totalAgents >= MAX_BETA_AGENTS) {
      return NextResponse.json(
        {
          success: false,
          error: `Ludwitt University is currently in limited beta with a cap of ${MAX_BETA_AGENTS} agents. You're on the waitlist — follow @ludwitt for updates on when the next cohort opens.`,
          waitlisted: true,
        },
        { status: 503 }
      )
    }
    const apiKey = generateApiKey()
    const apiKeyHash = hashSha256(apiKey)
    const now = new Date().toISOString()

    if (!existingCheckSnap.empty) {
      // Re-registration: rotate API key, update metadata
      const existingDoc = existingCheckSnap.docs[0]
      const existingProfile = existingDoc.data() as AgentProfile

      await existingDoc.ref.update({
        apiKeyHash,
        agentName: agentName.trim(),
        agentFramework,
        ...(description && { description: description.trim() }),
        lastSeenAt: now,
      })

      logger.info(
        'AgentRegister',
        `Agent re-registered: ${existingProfile.agentId}`
      )

      return successResponse({
        agentId: existingProfile.agentId,
        apiKey,
        reregistered: true,
        requiredCapabilities: REQUIRED_CAPABILITIES,
      })
    }

    // 5. New registration
    const agentRef = db.collection('agentProfiles').doc()
    const agentId = agentRef.id

    const profile: AgentProfile = {
      agentId,
      apiKeyHash,
      installFingerprintHash: fingerprintHash,
      agentName: agentName.trim(),
      agentFramework,
      ...(description && { description: description.trim() }),
      registeredAt: now,
      lastSeenAt: now,
      isProfessorEligible: false,
    }

    await agentRef.set(profile)

    // Create a university student profile for the agent
    const studentProfileRef = db
      .collection('universityStudentProfiles')
      .doc(agentId)
    await studentProfileRef.set({
      userId: agentId,
      completedCourses: [],
      totalXP: 0,
      enrolledAt: now,
      updatedAt: now,
      isAgent: true,
    })

    logger.info(
      'AgentRegister',
      `New agent registered: ${agentId} (${agentName.trim()})`
    )

    return successResponse({
      agentId,
      apiKey,
      reregistered: false,
      requiredCapabilities: REQUIRED_CAPABILITIES,
    })
  } catch (error) {
    return serverError(error, 'Failed to register agent')
  }
}
